module.exports = {

    fundamentalValues: [
//        'Infinity',
        'Nan',
//        'undefined',
        '__dirname',
        '__filename'
    ],

    globalFunctions: [
        'decodeURI',
        'decodeURIComponent',
        'encodeURI',
        'encodeURIComponent',
        'escape',
        'eval',
        'isFinite',
        'isNaN',
        'parseFloat',
        'parseInt',
        'unescape'    
    ],

    globalObjects: [
        'Object',
        'Function',
        'Boolean',
        'Symbol',
        'Error',
        'EvalError',
        'InternalError',
        'RangeError',
        'ReferenceError',
        'SyntaxError',
        'TypeError',
        'URIError',
        'Number',
        'Date',
        'Math',
        'String',
        'RegExp',
        'Array',
        'Int8Array',
        'Uint8Array',
        'Uint8ClampedArray',
        'Int16Array',
        'Uint16Array',
        'Int32Array',
        'Uint32Array',
        'Float32Array',
        'Float64Array',
        'Map',
        'Set',
        'WeakMap',
        'WeakSet',
        'ArrayBuffer',
        'SharedArrayBuffer ',
        'Atomics ',
        'DataView',
        'JSON',
        'Promise',
        'Generator',
        'GeneratorFunction',
        'AsyncFunction ',
        'Reflect',
        'Proxy',
        'Intl',
        'WebAssembly' 
    ]
}